name: Deploy Flask App to EC2

on:
  push:
    branches:
      - master  # Updated to match your branch name (use "main" if that's the actual branch)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Set the desired Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Set up SSH
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

    # Step 5: Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /var/www/flaskapp || exit
          git pull origin master || exit  # Use "master" if that's your branch
          source venv/bin/activate || exit
          pip install -r requirements.txt || exit
          sudo systemctl restart flaskapp || exit
        EOF

    # Step 6: Restart Nginx (optional)
    - name: Restart Nginx
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart nginx"
